apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab-runner.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "gitlab-runner.fullname" . }}
    chart: {{ include "gitlab-runner.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ default 1 .Values.replicas }}
  revisionHistoryLimit: {{ default 10 .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ include "gitlab-runner.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "gitlab-runner.fullname" . }}
        chart: {{ include "gitlab-runner.chart" . }}
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      containers:
      - name: {{ include "gitlab-runner.fullname" . }}
        image: {{ .Values.image.image }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        {{- include "gitlab-runner.unregisterRunners" . | nindent 8 }}
        command: ["/usr/bin/dumb-init", "--", "/bin/bash", "/configmaps/entrypoint"]
        env:
        {{ include "gitlab-runner.runner-env-vars" . | indent 8 }}
        volumeMounts:
        - name: etc-gitlab-runner
          mountPath: /home/gitlab-runner/.gitlab-runner
        - name: configmaps
          mountPath: /configmaps
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: etc-gitlab-runner
        emptyDir:
          medium: "Memory"
      - name: configmaps
        configMap:
          name: {{ include "gitlab-runner.fullname" . }}