apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: ClusterIP
  ingress_type: ingress
  hostname: awx.gorill.cloud
  postgres_storage_class: nfs-client
  projects_persistence: true
  projects_storage_access_mode: ReadWriteOnce
