apiVersion: v1
kind: Service
metadata:
  name: awx-lb-service
  namespace: awx
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/name: awx
    app.kubernetes.io/part-of: awx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8052
  selector:
    app.kubernetes.io/component: awx
    app.kubernetes.io/name: awx
  sessionAffinity: None
  type: LoadBalancer