{{- $fullName := include "traefik-forward-auth.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  namespace: {{ template "traefik-forward-auth.namespace" . }}
  labels:
  {{- include "traefik-forward-auth.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
  {{- include "traefik-forward-auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "traefik-forward-auth.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "traefik-forward-auth.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- with .Values.traefikForwardAuth }}
            {{- if .logging.level }}
            - name: LOG_LEVEL
              value: {{ .logging.level | quote }}
            {{- end }}
            {{- if .logging.format }}
            - name: LOG_FORMAT
              value: {{ .logging.format | quote }}
            {{- end }}
            {{- if .authHost }}
            - name: AUTH_HOST
              value: {{ .authHost | quote }}
            {{- end }}
            {{- if .cookie.domain }}
            - name: COOKIE_DOMAIN
              value: {{ .cookie.domain | quote }}
            {{- end }}
            {{- if .cookie.insecure }}
            - name: INSECURE_COOKIE
              value: {{ .cookie.insecure | quote }}
            {{- end }}
            {{- if .cookie.name }}
            - name: COOKIE_NAME
              value: {{ .cookie.name | quote }}
            {{- end }}
            {{- if .cookie.csrfName }}
            - name: CSRF_COOKIE_NAME
              value: {{ .cookie.csrfName | quote }}
            {{- end }}
            {{- if .default.action }}
            - name: DEFAULT_ACTION
              value: {{ .default.action | quote }}
            {{- end }}
            {{- if .default.provider }}
            - name: DEFAULT_PROVIDER
              value: {{ .default.provider | quote }}
            {{- end }}
            {{- if .restrictions.domain }}
            - name: DOMAIN
              value: {{ .restrictions.domain | quote }}
            {{- end }}
            {{- if .restrictions.whitelist }}
            - name: WHITELIST
              value: {{ .restrictions.whitelist | quote }}
            {{- end }}
            {{- if .lifetime }}
            - name: LIFETIME
              value: {{ .lifetime | quote }}
            {{- end }}
            {{- if .logoutRedirect }}
            - name: LOGOUT_REDIRECT
              value: {{ .logoutRedirect | quote }}
            {{- end }}
            {{- if .urlPath }}
            - name: URL_PATH
              value: {{ .urlPath | quote }}
            {{- end }}
            {{- if ne .secret "-" }}
            - name: SECRET
              {{- if .secret }}
              value: {{ .secret | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}
                  key: secret
              {{- end }}
              {{- end }}
            {{- with .providers }}
            {{- if .genericOauth.enabled }}
            {{- if .genericOauth.clientId }}
            - name: CLIENT_ID
              value: {{ .genericOauth.clientId | quote }}
            {{- end }}
            {{- if .genericOauth.clientSecret }}
            - name: CLIENT_SECRET
              value: {{ .genericOauth.clientSecret | quote }}
            {{- end }}
            {{- if .genericOauth.providerUri }}
            - name: PROVIDER_URI
              value: {{ .genericOauth.providerUri | quote }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if .Values.env }}
          {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 4181
              protocol: TCP
        {{- $livenessProbe := .Values.livenessProbe }}
        {{- if $livenessProbe.enabled }}
          livenessProbe:
          {{- $livenessProbe := unset $livenessProbe "enabled" }}
          {{- toYaml $livenessProbe | nindent 12 }}
        {{- end }}
        {{- $readinessProbe := .Values.readinessProbe }}
        {{- if $readinessProbe.enabled }}
          readinessProbe:
            {{- $readinessProbe := unset $readinessProbe "enabled" }}
            {{- toYaml $readinessProbe | nindent 12 }}
        {{- end }}
        {{- with .Values.resources }}
          resources:
      {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
