{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "traefik-forward-auth.fullname" . -}}
  {{- $svcPort := .Values.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ template "traefik-forward-auth.namespace" . }}
  labels:
  {{- include "traefik-forward-auth.labels" . | nindent 4 }}
  {{- if or .Values.ingress.annotations (and .Values.traefikForwardAuth.middleware.enabled .Values.traefikForwardAuth.authHost) }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if and .Values.traefikForwardAuth.middleware.enabled .Values.traefikForwardAuth.authHost }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ .Values.traefikForwardAuth.middleware.name | default "traefik-forward-auth" }}@kubernetescrd
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  routes:
    - match: {{ .Values.ingress.host }}
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
{{- end }}
