apiVersion: v1
name: gitlab-runner
version: 0.0.13
appVersion: bleeding
description: GitLab Runner
keywords:
- git
- ci
- deploy
icon: https://gitlab.com/uploads/-/system/project/avatar/250833/runner_logo.png
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
