apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/kompose-default: "true"
        io.kompose.service: broker
    spec:
      containers:
        - image: docker.io/library/redis:7
          name: broker
          ports:
            - containerPort: 6379
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: redisdata
      restartPolicy: Always
      volumes:
        - name: redisdata
          persistentVolumeClaim:
            claimName: redisdata
status: {}
