apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tika
  name: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tika
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/kompose-default: "true"
        io.kompose.service: tika
    spec:
      containers:
        - image: ghcr.io/paperless-ngx/tika:latest
          name: tika
          ports:
            - containerPort: 9998
              hostPort: 9998
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
