apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: tika
  name: tika
spec:
  ports:
    - name: "9998"
      port: 9998
      targetPort: 9998
  selector:
    io.kompose.service: tika
status:
  loadBalancer: {}
