apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/kompose-default: "true"
        io.kompose.service: webserver
    spec:
      containers:
        - env:
            - name: PAPERLESS_DBENGINE
              value: mariadb
            - name: PAPERLESS_DBHOST
              value: db
            - name: PAPERLESS_DBPASS
              value: paperless
            - name: PAPERLESS_DBPORT
              value: "3306"
            - name: PAPERLESS_DBUSER
              value: paperless
            - name: PAPERLESS_REDIS
              value: redis://broker:6379
            - name: PAPERLESS_TIKA_ENABLED
              value: "1"
            - name: PAPERLESS_TIKA_ENDPOINT
              value: http://tika:9998
            - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
              value: http://gotenberg:3000
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8000
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: webserver
          ports:
            - containerPort: 8000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/paperless/data
              name: data
            - mountPath: /usr/src/paperless/media
              name: media
            - mountPath: /usr/src/paperless/export
              name: webserver-claim2
            - mountPath: /usr/src/paperless/consume
              name: webserver-claim3
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: webserver-claim2
          persistentVolumeClaim:
            claimName: webserver-claim2
        - name: webserver-claim3
          persistentVolumeClaim:
            claimName: webserver-claim3
status: {}
