apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grocy-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: x-auth-request-user, x-auth-request-email, x-auth-request-access-token, x-user, x-forwarded-user
    nginx.ingress.kubernetes.io/auth-signin: https://oauth.gorill.cloud/oauth2/start?rd=$scheme://$best_http_host$request_uri
    nginx.ingress.kubernetes.io/auth-url: https://oauth.gorill.cloud/oauth2/auth
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
spec:
  rules:
  - host: "grocy.gorill.cloud"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grocy
            port:
              number: 80