apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grocy-ingress-api
  annotations:
    {{- with .Values.ingressapi.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}    
spec:
  rules:
  - host: "grocy.gorill.cloud"
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: grocy
            port:
              number: 80